/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.ModelTables.ModelTableContraseñas;
import com.istloja.controlador.Contraseñasbd;

/**
 *
 * @author ANDRES
 */
public class BusquedaAvanzada extends javax.swing.JDialog {

    /**
     * Creates new form BusquedaAvanzada
     */
    private ModelTableContraseñas modelTableContraseñas;
    private Contraseñasbd controladorContraseñas;
    
    public BusquedaAvanzada(java.awt.Frame parent, boolean modal, ModelTableContraseñas modelTableContraseñas, 
            Contraseñasbd controladorContraseñas) {
        super(parent, modal);
        this.modelTableContraseñas = modelTableContraseñas;
        this.controladorContraseñas = controladorContraseñas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscarRegistroContraseñascbx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxBuscarContraseñas = new javax.swing.JComboBox<>();
        txtBuscarContraseñascbx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(modelTableContraseñas);
        jScrollPane1.setViewportView(jTable1);

        btnBuscarRegistroContraseñascbx.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBuscarRegistroContraseñascbx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/imagenes/buscar.png"))); // NOI18N
        btnBuscarRegistroContraseñascbx.setText("Buscar");
        btnBuscarRegistroContraseñascbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRegistroContraseñascbxActionPerformed(evt);
            }
        });

        jLabel1.setText("Busqueda");

        cbxBuscarContraseñas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Nombre Sitio Web", "Usuario" }));

        jLabel2.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel2.setText("Registro de Contraseñas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxBuscarContraseñas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtBuscarContraseñascbx, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarRegistroContraseñascbx)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxBuscarContraseñas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarContraseñascbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarRegistroContraseñascbx)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRegistroContraseñascbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRegistroContraseñascbxActionPerformed
        // TODO add your handling code here:
        System.out.println("Combo" +cbxBuscarContraseñas.getSelectedIndex());
        switch (cbxBuscarContraseñas.getSelectedIndex()){
            case 0:
                modelTableContraseñas.fireTableDataChanged();
            case 1: //CODIGO
                modelTableContraseñas.setUsuarios(controladorContraseñas.buscarContraseñaNombreSitioWebCombo(txtBuscarContraseñascbx.getText()));
                modelTableContraseñas.fireTableDataChanged();
                break; 
            case 2: //DESCRIPCION
                modelTableContraseñas.setUsuarios(controladorContraseñas.buscarUsuariosCombo(txtBuscarContraseñascbx.getText()));
                modelTableContraseñas.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnBuscarRegistroContraseñascbxActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRegistroContraseñascbx;
    private javax.swing.JComboBox<String> cbxBuscarContraseñas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscarContraseñascbx;
    // End of variables declaration//GEN-END:variables
    
}
