/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.ModelTables.ComunicacionTablas;
import com.istloja.ModelTables.ModelTableContraseñas;
import com.istloja.controlador.Contraseñasbd;
import com.istloja.modelo.Usuarios;
import com.istloja.modelo.Utilidades;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author ANDRES
 */
public class GestionarContraseñas extends javax.swing.JFrame implements ComunicacionTablas{

    private Utilidades utilidades;
    private Contraseñasbd controladorUsuariosContraseña;
    private ModelTableContraseñas modelTableContraseñas;
    private Contraseñas contraseñasgestion;
    private Usuarios usuariosEditar;
    
    /**
     * Creates new form NewJFrame
     */
    public GestionarContraseñas() {
        controladorUsuariosContraseña = new Contraseñasbd();
        modelTableContraseñas = new ModelTableContraseñas(controladorUsuariosContraseña.obtenerRegistros(), this);
        initComponents();
        this.setLocationRelativeTo(null);
        contraseñasgestion = new Contraseñas(txtNombreSitioWeb, txtDireccionSitioWeb, txtUsuario, txtContraseña, txtCorreoRecuperacion, this);
        txtFechaRegistro.setText(new Date().toString());
        txtFechaRegistro.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JPgestorContraseñas = new javax.swing.JPanel();
        lblNombreSitioWeb = new javax.swing.JLabel();
        lblDireccionSitioWeb = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblCorreoRecuperacion = new javax.swing.JLabel();
        lblFechaRegistro = new javax.swing.JLabel();
        txtNombreSitioWeb = new javax.swing.JTextField();
        txtDireccionSitioWeb = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtCorreoRecuperacion = new javax.swing.JTextField();
        txtFechaRegistro = new javax.swing.JTextField();
        btnAbrirLink = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        btnEliminar = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        btnMostrarTablaRegistros = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditarContraseñas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMacercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        JPgestorContraseñas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestionar Contraseñas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DialogInput", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        JPgestorContraseñas.setForeground(new java.awt.Color(153, 204, 255));
        JPgestorContraseñas.setToolTipText("");

        lblNombreSitioWeb.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblNombreSitioWeb.setText("Nombre Sitio Web");

        lblDireccionSitioWeb.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblDireccionSitioWeb.setText("Direccion Sitio Web");

        lblUsuario.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblUsuario.setText("Usuario");

        lblContraseña.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblContraseña.setText("Contraseña");

        lblCorreoRecuperacion.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblCorreoRecuperacion.setText("Correo de Recuperacion");

        lblFechaRegistro.setBackground(new java.awt.Color(0, 0, 0));
        lblFechaRegistro.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblFechaRegistro.setText("Fecha de Registro");

        txtNombreSitioWeb.setToolTipText("Ingrese el nombre del Sitio Web");
        txtNombreSitioWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreSitioWebMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreSitioWebMouseExited(evt);
            }
        });

        txtDireccionSitioWeb.setToolTipText("Ingrese la Direccion URL del sitio web");
        txtDireccionSitioWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDireccionSitioWebMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDireccionSitioWebMouseExited(evt);
            }
        });

        txtUsuario.setToolTipText("Ingrese el usuario");
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseExited(evt);
            }
        });

        txtCorreoRecuperacion.setToolTipText("Ingrese el correo de recuperación de la contraseña");
        txtCorreoRecuperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCorreoRecuperacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCorreoRecuperacionMouseExited(evt);
            }
        });

        txtFechaRegistro.setToolTipText("Fecha de registro");

        btnAbrirLink.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnAbrirLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/imagenes/enlace.png"))); // NOI18N
        btnAbrirLink.setText("Abrir Link");
        btnAbrirLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirLinkActionPerformed(evt);
            }
        });

        txtContraseña.setToolTipText("Ingrese la contraseña");
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JPgestorContraseñasLayout = new javax.swing.GroupLayout(JPgestorContraseñas);
        JPgestorContraseñas.setLayout(JPgestorContraseñasLayout);
        JPgestorContraseñasLayout.setHorizontalGroup(
            JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPgestorContraseñasLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreSitioWeb)
                    .addComponent(lblFechaRegistro)
                    .addComponent(lblDireccionSitioWeb)
                    .addComponent(lblUsuario)
                    .addComponent(lblContraseña)
                    .addComponent(lblCorreoRecuperacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionSitioWeb, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreoRecuperacion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreSitioWeb, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaRegistro)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnAbrirLink)
                .addContainerGap())
        );
        JPgestorContraseñasLayout.setVerticalGroup(
            JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPgestorContraseñasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreSitioWeb)
                    .addComponent(txtNombreSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionSitioWeb)
                    .addComponent(txtDireccionSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrirLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreoRecuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreoRecuperacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPgestorContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaRegistro))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(153, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(153, 102, 255));
        btnLimpiarCampos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/imagenes/escoba.png"))); // NOI18N
        btnLimpiarCampos.setText("Limpiar");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnMostrarTablaRegistros.setBackground(new java.awt.Color(153, 102, 255));
        btnMostrarTablaRegistros.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnMostrarTablaRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/imagenes/frecuencia.png"))); // NOI18N
        btnMostrarTablaRegistros.setText("Mostrar Tabla de Registros");
        btnMostrarTablaRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTablaRegistrosActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(153, 102, 255));
        btnGuardar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/imagenes/disco-flexible.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditarContraseñas.setBackground(new java.awt.Color(153, 102, 255));
        btnEditarContraseñas.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnEditarContraseñas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/imagenes/editar.png"))); // NOI18N
        btnEditarContraseñas.setText("Editar");
        btnEditarContraseñas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContraseñasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JPgestorContraseñas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnEditarContraseñas)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCampos)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarTablaRegistros)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(JPgestorContraseñas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarTablaRegistros)
                    .addComponent(btnLimpiarCampos)
                    .addComponent(btnEditarContraseñas)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        JMacercaDe.setText("Acerda De");
        JMacercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMacercaDeMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMacercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        GuardarContraseñas();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnMostrarTablaRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTablaRegistrosActionPerformed
        // TODO add your handling code here:
        BusquedaAvanzada dialog = new BusquedaAvanzada(new javax.swing.JFrame(),
                true, modelTableContraseñas, controladorUsuariosContraseña);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnMostrarTablaRegistrosActionPerformed

    private void btnEditarContraseñasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContraseñasActionPerformed
        // TODO add your handling code here:
        EditarContraseñas();
    }//GEN-LAST:event_btnEditarContraseñasActionPerformed

    private void btnAbrirLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirLinkActionPerformed
        // TODO add your handling code here:
        AbrirLink();
    }//GEN-LAST:event_btnAbrirLinkActionPerformed

    private void JMacercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMacercaDeMouseClicked
        // TODO add your handling code here:
        Informacion pantalla = new Informacion(this, true);
        pantalla.setVisible(true);
    }//GEN-LAST:event_JMacercaDeMouseClicked

    private void txtNombreSitioWebMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreSitioWebMouseEntered
        // TODO add your handling code here
        txtNombreSitioWeb.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_txtNombreSitioWebMouseEntered

    private void txtNombreSitioWebMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreSitioWebMouseExited
        // TODO add your handling code here:
        txtNombreSitioWeb.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNombreSitioWebMouseExited

    private void txtDireccionSitioWebMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionSitioWebMouseEntered
        // TODO add your handling code here:
        txtDireccionSitioWeb.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_txtDireccionSitioWebMouseEntered

    private void txtDireccionSitioWebMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionSitioWebMouseExited
        // TODO add your handling code here:
        txtDireccionSitioWeb.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtDireccionSitioWebMouseExited

    private void txtUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseEntered
        // TODO add your handling code here:
        txtUsuario.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_txtUsuarioMouseEntered

    private void txtUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseExited
        // TODO add your handling code here:
        txtUsuario.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtUsuarioMouseExited

    private void txtContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseEntered
        // TODO add your handling code here:
        txtContraseña.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_txtContraseñaMouseEntered

    private void txtContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseExited
        // TODO add your handling code here:
        txtContraseña.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtContraseñaMouseExited

    private void txtCorreoRecuperacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoRecuperacionMouseEntered
        // TODO add your handling code here:
        txtCorreoRecuperacion.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_txtCorreoRecuperacionMouseEntered

    private void txtCorreoRecuperacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoRecuperacionMouseExited
        // TODO add your handling code here:
        txtCorreoRecuperacion.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtCorreoRecuperacionMouseExited

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        EliminarUsuarios();
    }//GEN-LAST:event_btnEliminarActionPerformed

    
//------------------------------------------------------------------------------------------------------------------------------------------------------
    //METODOS PARA GESTIONAR EL PROYECTO
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void LimpiarCampos(){
        txtNombreSitioWeb.setText("");
        txtDireccionSitioWeb.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtCorreoRecuperacion.setText("");
        txtFechaRegistro.setText("");
        
    }
    void actualizarTablaRegistros(){
        List<Usuarios> tablaActualizadaInventarios = controladorUsuariosContraseña.obtenerRegistros();
        modelTableContraseñas.setUsuarios(tablaActualizadaInventarios);
        modelTableContraseñas.fireTableDataChanged();
    }
    
    public void GuardarContraseñas(){
        Usuarios guardarUsuarios = contraseñasgestion.guardarContraseñas(true);
        
        if(guardarUsuarios != null){
            if(controladorUsuariosContraseña.RegistrarContraseña(guardarUsuarios)){
                guardarUsuarios.setFecha_registro(new Date());
                JOptionPane.showMessageDialog(rootPane, "Inventario guardado con éxito del sitema.");
                LimpiarCampos();
                actualizarTablaRegistros();
            }else{
                JOptionPane.showMessageDialog(rootPane, "ERRROR.");

            }
        }
    }
    
    public void EditarContraseñas(){
        Usuarios editarUsuarios = contraseñasgestion.guardarContraseñas(true);
        
        if(editarUsuarios != null){
            editarUsuarios.setIdUsuarios(usuariosEditar.getIdUsuarios());
            if(controladorUsuariosContraseña.editarContraseña(editarUsuarios)){
                JOptionPane.showMessageDialog(rootPane, "Editado Correctamente");
                LimpiarCampos();
                usuariosEditar = null;
                actualizarTablaRegistros();
            }
        }
    }
    
    public void AbrirLink(){
        Desktop enlace = Desktop.getDesktop();
        String enlaceAcceder = usuariosEditar.getDireccionWeb();
        try {
            enlace.getDesktop().browse(new URI(enlaceAcceder));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No se puede abrir el link"+e);
        }
    }
    
    //METODO PARA ELIMINAR UNA PERSONA.
    public void EliminarUsuarios(){
        if(usuariosEditar != null){
            if(controladorUsuariosContraseña.EliminarRegistro(usuariosEditar)){
                JOptionPane.showMessageDialog(rootPane, "Eliminado Correctamente");
                LimpiarCampos();
                actualizarTablaRegistros();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Se ha Eliminado Correctamente");
                actualizarTablaRegistros();
                LimpiarCampos();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "No hay persona");
            actualizarTablaRegistros();
            LimpiarCampos();
            }
    }
    
    // </editor-fold>
//------------------------------------------------------------------------------------------------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarContraseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarContraseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarContraseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarContraseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarContraseñas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMacercaDe;
    private javax.swing.JPanel JPgestorContraseñas;
    private javax.swing.JButton btnAbrirLink;
    private javax.swing.JButton btnEditarContraseñas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnMostrarTablaRegistros;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreoRecuperacion;
    private javax.swing.JLabel lblDireccionSitioWeb;
    private javax.swing.JLabel lblFechaRegistro;
    private javax.swing.JLabel lblNombreSitioWeb;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreoRecuperacion;
    private javax.swing.JTextField txtDireccionSitioWeb;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtNombreSitioWeb;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    
   public void clickUsuarios(Usuarios u){
       System.out.println("Usuarios" +u.toString());
       txtNombreSitioWeb.setText(u.getNombresSitioWeb());
       txtDireccionSitioWeb.setText(u.getDireccionWeb());
       txtUsuario.setText(u.getUsuario());
       txtContraseña.setText(u.getContraseña());
       txtCorreoRecuperacion.setText(u.getCorreo_recuperacion());
       txtFechaRegistro.setText(u.getFecha_registro().toString());
       clickAbrirLink(u);
       usuariosEditar = u; 
   }
   
    int contadorClick = 0;  
    boolean ejecutar;
    @Override
    public void clickAbrirLink(Usuarios us){
        ejecutar = true;
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (ejecutar){
                    try {
                        Thread.sleep(1000);
                        contadorClick = 0;
                        ejecutar = false;
                        System.out.println("Reinicia CLICK");
                    } catch (InterruptedException e) {
                        System.out.println(e.getMessage());
                    }
                }
            }
        }).start();
        contadorClick++;
        if(contadorClick == 2){
            if(JOptionPane.showConfirmDialog(rootPane, "Se Ingresara al link, ¿Desea Continuar?",
                    "Ingresar al Link", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            AbrirLink();
            }
            contadorClick = 0;
            ejecutar = false;
        }
        System.out.println("contadorClick" +contadorClick);
    }
}
